### ISSUE TITLE
Endpoint is legacy

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/sql-query#3]
Fix as follows like "*.cloud-object-storage.appdomain.cloud"
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-endpoints

**Comment by blhatdeibmcom** [comment]
@khayama Can you please clarify what, exactly, you are requesting? All the entries shown in
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-endpoints
already have the form ***.cloud-object-storage.appdomain.cloud.**

**Comment by khayama** [comment]
This is the issue for the docs about SQL query.
I mean I would like you to fix your SQL docs with the new COS endpoint replacing the legacy one.

**Comment by blhatdeibmcom** [comment]
@khayama Do you mean that we need to change the endpoints listed in
https://cloud.ibm.com/docs/services/sql-query?topic=sql-query-overview
from ***.objectstorage.service.networklayer.com** and ***.objectstorage.softlayer.net** to ***.cloud-object-storage.appdomain.cloud**? Or do you mean something else? (If you mean something else, please be as specific as you can about what you mean by "your SQL docs".)

**Comment by khayama** [comment]
Yes

>Do you mean that we need to change the endpoints listed in
https://cloud.ibm.com/docs/services/sql-query?topic=sql-query-overview
from *.objectstorage.service.networklayer.com and *.objectstorage.softlayer.net to *.cloud-object-storage.appdomain.cloud?

**Comment by blhatdeibmcom** [comment]
@andrealang Can you make the change that @khayama is requesting?

**Comment by andrealang** [comment]
@khayama @blhatdeibmcom I made the changes, should be online on prod within the next 30-60 mins.
